#!/usr/bin/env python3
"""Generate nginx include with /p/<name> short install links from dist/plugins.json."""
import json
from pathlib import Path

root = Path('/Users/eno/workspace/dshstore')
j = json.loads((root / 'dist/plugins.json').read_text())
lines = ['# /p/ short install links (generated by deploy/gen_p_short.py)']
for p in j['plugins']:
    lines.append('location = /p/' + p['name'] + ' { return 302 /plugins/' + p['name'] + '-' + p['version'] + '.tgz?src=p; }')
out = (root / 'deploy' / 'whaleharness-p-short.inc')
out.write_text(chr(10).join(lines) + chr(10))
print('wrote', out, len(lines) - 1, 'links')